<a href="https://colab.research.google.com/github/MUTHUKRISHNAN123/sample/blob/main/Ex_No_8_Programs_on_Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

8.1 Test whether any of the elements of a given array is non-zero.

In [2]:
import numpy as np
z=np.array([1,2,3,4,5,6,7,8,9,0])
print(z)
print(np.all(z))  #np.all() function return true if o is not present in array.

[1 2 3 4 5 6 7 8 9 0]
False


8.2 Test element-wise for NaN of a given array.

In [3]:
import numpy as np
z=np.array([1,2,3,4,5,6,7,8,9,0,np.nan,np.inf])
print(z)
print(np.isnan(z))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.  0. nan inf]
[False False False False False False False False False False  True False]


8.3 Create an element-wise comparison (greater, greater_equal, less
 and less_equal) of two given arrays.

In [4]:
x=np.arange(5,20,2)
y=np.arange(15,30,2)
print(x)
print(y)
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[ 5  7  9 11 13 15 17 19]
[15 17 19 21 23 25 27 29]
[False False False False False False False False]
[False False False False False False False False]
[ True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True]


8.4 create a vector with values ranging from 50 to 90 and print all values except the first and last.

In [6]:
z=np.arange(50,90,1)
print(z)
print('printing all values except the first and last')
print(z[1:-1])

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]
printing all values except the first and last
[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88]


8.5 sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [17]:
z=np.array([[100,90],[80,70]])
print(z)
print("sorting along first axis")
print(np.sort(z,axis=0))
print("sorting along last axis")
print(np.sort(z))
print('flatened array')
print(np.sort(z,axis=None))

[[100  90]
 [ 80  70]]
sorting along first axis
[[ 80  70]
 [100  90]]
sorting along last axis
[[ 90 100]
 [ 70  80]]
flatened array
[ 70  80  90 100]


8.6 Get the indices of the sorted elements of a given array.

In [25]:
x=np.array([2,67,3,56,10,23,4])
y=np.arange(5,10,1)
print(x)
print(y)
print("the indices of sorted elements in array")
print(np.argsort(x))
print(np.argsort(y))

[ 2 67  3 56 10 23  4]
[5 6 7 8 9]
the indices of sorted elements in array
[0 2 6 4 5 3 1]
[0 1 2 3 4]


8.7 get the minimum and maximum value of a given array along the second axis.

In [34]:
z=np.array([[5000,700],[89,90]])
print(z)
print('the maximum value is:',np.amax(z,1))
print('the minimum value is:',np.amin(z,1))


[[5000  700]
 [  89   90]]
the maximum value is: [5000   90]
the minimum value is: [700  89]


8.8 calculate the difference between the maximum and the minimum values of a given array along the second axis.

In [36]:
z=np.array([[5000,700],[89,90]])
print(z)
x=np.amax(z,1)
y=np.amin(z,1)
print('the difference is:',x-y)

[[5000  700]
 [  89   90]]
the difference is: [4300    1]


8.9 compute the mean, standard deviation, and variance of a given array along the second axis.

In [43]:
z=np.arange(10)
print(z)
print("the mean is: ",np.mean(z))
#SD = np.sqrt(np.mean((z-np.mean(z))**2))  #np.sqrt(np.mean((array - np.mean(array)) ** 2))
print("the standard deviation is: ",np.std(z)) 
# for var np.mean((z-np.mean(z))**2)
print("the variance is: ",np.var(z))


[0 1 2 3 4 5 6 7 8 9]
the mean is:  4.5
the standard deviation is:  2.8722813232690143
the variance is:  8.25


8.10 compute the covariance matrix of two given arrays

In [47]:
x=np.arange(5)
y=np.arange(5,10)
print(x)
print(y)
print("the covariance matrix of x & y is:\n ",np.cov(x,y))

[0 1 2 3 4]
[5 6 7 8 9]
the covariance matrix of x & y is:
  [[2.5 2.5]
 [2.5 2.5]]


8.11 compute the determinant of a given square array.

In [49]:
from numpy import linalg
z=np.array([[4,7,10],[5,7,9],[10,13,7]])
print(z)
print("the determinant is:",np.linalg.det(z))

[[ 4  7 10]
 [ 5  7  9]
 [10 13  7]]
the determinant is: 63.00000000000005


8.12 compute the sum of the diagonal element of a given array.

In [50]:
z=np.array([[4,7,10],[5,7,9],[10,13,7]])
print(z)
print("the sum of diagonal elements is: ",np.trace(z))
a=np.diagonal(z)
print("the diagonal is:",a)
print(sum(a))

[[ 4  7 10]
 [ 5  7  9]
 [10 13  7]]
the sum of diagonal elements is:  18
the diagonal is: [4 7 7]
18
